DROP TABLE IF EXISTS SALES  CASCADE;
DROP TABLE IF EXISTS VEGETABLES CASCADE;

CREATE TABLE VEGETABLES
(
	VegId INT PRIMARY KEY
	,Name VARCHAR(50) NOT NULL
	,Variety VARCHAR(50) NOT NULL
	,PrimaryColor VARCHAR(50) NOT NULL
	,LifeTime INT NOT NULL CHECK (LifeTime >= 0)
	,Fresh SMALLINT NOT NULL  CHECK (Fresh = 0 OR Fresh = 1) DEFAULT  0
);

CREATE TABLE SALES
(
	SaleId SERIAL PRIMARY KEY
	,SaleDate DATE NOT NULL
	,SaleWeight INT NOT NULL CHECK(SaleWeight >= 1)
	,SaleUnitPrice DECIMAL(5,2) NOT NULL CHECK (SaleunitPrice >= 0)
	,SaleActive SMALLINT NOT NULL CHECK (SaleActive = 0 OR SaleActive = 1)
	,VegId INT NOT NULL
);

ALTER TABLE SALES
	ADD CONSTRAINT FK_SALES_VEGETABLES FOREIGN KEY (VegId) REFERENCES VEGETABLES (VegId);
