DROP TABLE IF EXISTS POSSESS;
DROP TABLE IF EXISTS CARS;
DROP TABLE IF EXISTS OWNERS;
DROP TABLE IF EXISTS BRANDS;

CREATE TABLE OWNERS
(
	owner_id SERIAL PRIMARY KEY,
	owner_lastname VARCHAR(50) NOT NULL,
	owner_firstname VARCHAR(50) NOT NULL
);

CREATE TABLE BRANDS
(
	brand_id SERIAL PRIMARY KEY,
	brand_name VARCHAR(50) NOT NULL,
	brand_slogan VARCHAR(255) NULL
);

CREATE TABLE CARS
(
	car_id SERIAL PRIMARY KEY,
	car_name VARCHAR(100) NOT NULL,
	brand_id INT NOT NULL
);

CREATE TABLE POSSESS
(
	car_id INT,
	owner_id INT,
	car_registration CHAR(9) NOT NULL
);

ALTER TABLE CARS
ADD CONSTRAINT FK_CARS_BRANDS FOREIGN KEY (brand_id) REFERENCES BRANDS (brand_id);

ALTER TABLE POSSESS
ADD CONSTRAINT PK_POSSESS_OWNERS_CARS PRIMARY KEY(car_id,owner_id),
ADD CONSTRAINT FK_POSSESS_CARS FOREIGN KEY (car_id) REFERENCES CARS (car_id),
ADD CONSTRAINT FK_POSSESS_OWNERS FOREIGN KEY (owner_id) REFERENCES OWNERS (owner_id);