DROP TABLE IF EXISTS CITIES;
DROP TABLE IF EXISTS COUNTRIES;

CREATE TABLE CITIES
(
	city_id SERIAL PRIMARY KEY,
	city_name VARCHAR(100) NOT NULL,
	country_code CHAR(2) NOT NULL
);

CREATE TABLE COUNTRIES
(
	country_code CHAR(2) PRIMARY KEY,
	country_name VARCHAR(100) NOT NULL
);

ALTER TABLE CITIES
ADD CONSTRAINT FK_CITIES_COUNTRIES 
FOREIGN KEY (country_code) REFERENCES COUNTRIES (country_code);
